name: Terraform Linting and Deployment

on:
  push:
    branches:
      - main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Replace with the version you are using

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    # Run TFLint and Terraform for 'network' directory
    - name: Run TFLint on Network
      working-directory: vpc_prod/network
      run: |
        tflint --init
        tflint

    - name: Terraform Init and Apply for Network
      working-directory: vpc_prod/network
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        terraform init
        terraform apply -auto-approve

    # Run TFLint and Terraform for 'webserver' directory
    - name: Run TFLint on Webserver
      working-directory: vpc_prod/webserver
      run: |
        tflint --init
        tflint

    - name: Terraform Init and Apply for Webserver
      working-directory: vpc_prod/webserver
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply -auto-approve
